---
title: "DataScript"
output: html_document
---

```{r setup, include=FALSE}
#Set up library 
library(googlesheets4)
library(janitor)
library(tidyverse)
library(dplyr)
library(rlang)

#Data Loadin  
dat <- read_sheet("https://docs.google.com/spreadsheets/d/1h1ZudRdrVLPs_HSrMyJs0rd5kMD5vNh6D0ZvEeYN45g/edit#gid=0")

#this uses the janitor package to clean up the names so that there are no spaces. 
#the names are still too long. 
dat <- clean_names(dat)

#So we write out a list of the names of the columns we would like in the order they will be used. 
shortname <- c("years",
"sector_my",
"role_my",
"my_region",
"acc_type",
"sector_mature",
"sector_should",
"role_success",
"role_should",
"gov_path",
"who_should",
"diff_bounties",
"diff_public_bodies",
"diff_open_audit_tool",
"diff_public_procurement",
"diff_impact_assess",
"diff_audit",
"diff_direct_sh",
"diff_antic_interest_sh",
"diff_disp_outcome",
"diff_dataset_acc",
"diff_expl",
"matur_bounties",
"matur_public_bodies",
"matur_open_audit_tool",
"matur_public_procurement",
"matur_impact_assess",
"matur_audit",
"matur_direct_sh",
"matur_antic_interest_sh",
"matur_disp_outcome",
"matur_dataset_acc",
"matur_expl",
"obstacles",
"promising_area",
"comment")

#Rename columns with the list of short column names (names are too long otherwise)
colnames(dat) <- c(shortname)

#add an index number for working with multiple select questions
dat$index <- 1:nrow(dat)

```



```{r, functions & generate charts}

#Build a function for multi-select questions to get counts and percentages for multiple select questions (meaning there are multiple things that the respondent can select)

mult_select <- function(dat, mscol, index) {
    newdf <- dat %>% 
    select({{ mscol }}, {{ index }}) %>%
    separate_rows({{ mscol }}, sep = ", ") %>% 
    count({{ mscol }}, sort = TRUE ) %>% 
    mutate(
      percent = paste(round(n/sum(n)*100,2), "%")
    ) %>%
    rename(
      opinion = 1
    ) %>%
  return(newdf)
  }

#first we select the data column and the index column 
#then we split the data separated by commas, 
#index shows who said what combination of answers 
    
#Charts for each of the multiple select variables 
cht_role_success <- mult_select(dat, role_success, index)
cht_role_should <- mult_select(dat, role_should, index)
cht_obstacles <- mult_select(dat, obstacles, index)
cht_promising <- mult_select(dat, promising_area, index)

#List of what should be included in spreadsheet
MSCharts <- list(role_success = cht_role_success, 
                 role_should = cht_role_should, 
                 obstacles = cht_obstacles, 
                 promising = cht_promising)


#Basic Chart Function w/o multiple select 
basic_chart <- function(dat, mscol, index) {
    newdf <- dat %>% 
    select({{ mscol }}, {{ index }}) %>%
    count({{ mscol }}, sort = TRUE ) %>% 
    mutate(
      percent = paste(round(n/sum(n)*100,2), "%")
    ) %>% 
      rename(
      opinion = 1
    ) %>%
  return(newdf)
  }
 
#Make charts for Basic Chart Chunk #1 (data is counts of variables)
cht_who_should <- basic_chart(dat, who_should, index)
cht_years <- basic_chart(dat, years, index)
cht_sector_my <- basic_chart(dat, sector_my, index)
cht_my_region <- basic_chart(dat, my_region, index)
cht_acc_type <- basic_chart(dat, acc_type, index)
cht_sector_mature <- basic_chart(dat, sector_mature, index)
cht_sector_should <- basic_chart(dat, sector_should, index)
cht_gov_path <- basic_chart(dat, gov_path, index)

#List of what should be included in spreadsheet for Basic Chart Chunk #1 
BasicCharts1 <- list(who_should = cht_who_should, 
                     years = cht_years, 
                     sector_my = cht_sector_my, 
                     my_region = cht_my_region, 
                     acc_type = cht_acc_type, 
                     sector_mature = cht_sector_mature, 
                     sector_should = cht_sector_should,
                     gov_path = cht_gov_path)

#charts for Basic Chart Chunk #2 (data is likert scale easy/difficult)
cht_diff_bounties <- basic_chart(dat, diff_bounties, index)
cht_diff_public_bodies <- basic_chart(dat, diff_public_bodies, index)
cht_diff_open_audit_tool <- basic_chart(dat, diff_open_audit_tool, index)
cht_diff_public_procurement <- basic_chart(dat, diff_public_procurement, index)
cht_diff_impact_assess <- basic_chart(dat, diff_impact_assess, index)
cht_diff_audit <- basic_chart(dat, diff_audit, index)
cht_diff_direct_sh <- basic_chart(dat, diff_direct_sh, index)
cht_diff_antic_interest_sh <- basic_chart(dat, diff_antic_interest_sh, index)
cht_diff_disp_outcome <- basic_chart(dat, diff_disp_outcome, index)
cht_diff_dataset_acc <- basic_chart(dat, diff_dataset_acc, index)
cht_diff_expl <- basic_chart(dat, diff_expl, index)

#List of what should be included in Basic Chart Chunk #2 spreadsheet
BasicCharts2 <- list(
          bounties = cht_diff_bounties, 
          public_bodies = cht_diff_public_bodies, 
          open_audit_model = cht_diff_open_audit_tool, 
          public_procurement = cht_diff_public_procurement, 
          impact_assess = cht_diff_impact_assess, 
          audit = cht_diff_audit, 
          direct_sh = cht_diff_direct_sh, 
          antic_interest = cht_diff_antic_interest_sh, 
          disp_outcome = cht_diff_disp_outcome, 
          dataset_acc = cht_diff_dataset_acc, 
          expl = cht_diff_expl)

#charts for Basic Chart Chunk #3 (data is likert scale immature/mature)
cht_matur_bounties <- basic_chart(dat, matur_bounties, index)
cht_matur_public_bodies <- basic_chart(dat, matur_public_bodies, index)
cht_matur_open_audit_tool <- basic_chart(dat, matur_open_audit_tool, index)
cht_matur_public_procurement <- basic_chart(dat, matur_public_procurement, index)
cht_matur_impact_assess <- basic_chart(dat, matur_impact_assess, index)
cht_matur_direct_sh <- basic_chart(dat, matur_direct_sh, index)
cht_matur_antic_interest_sh <- basic_chart(dat, matur_antic_interest_sh, index)
cht_matur_disp_outcome <- basic_chart(dat, matur_disp_outcome, index)
cht_matur_dataset_acc <- basic_chart(dat, matur_dataset_acc, index)
cht_matur_expl <- basic_chart(dat, matur_expl, index)


#List of what should be included in spreadsheet Basic Chart Chunk #3
BasicCharts3 <- list(
  bounties = cht_matur_bounties, 
  public_bodies = cht_matur_public_bodies, 
  open_audit_tool = cht_matur_open_audit_tool, 
  public_procurement = cht_matur_public_procurement, 
  impact_assess = cht_matur_impact_assess, 
  direct_sh = cht_matur_direct_sh, 
  antic_interest_sh = cht_matur_antic_interest_sh, 
  disp_outcome = cht_matur_disp_outcome, 
  dataset_acc = cht_matur_dataset_acc, 
  expl = cht_matur_expl)



```


```{r, run googlesheets}
#Write each of these four chunks to four Gsheets 

#ss <- gs4_create("ACL_MSCharts", 
#                 sheets = MSCharts)

#ss <- gs4_create("ACL_BasicCharts1", 
#                 sheets = BasicCharts1)

#ss <- gs4_create("ACL_BasicCharts2", 
#                 sheets = BasicCharts2)

#ss <- gs4_create("ACL_BasicCharts3", 
#                 sheets = BasicCharts3)


``` 



```{r, Extras}
#How to do it without function- DONT USE  
#cht_role_select <- dat %>% 
#  select(index, role_success) %>% 
#          separate_rows(role_success,  
#                     sep = ", ") %>% 
#          count(role_success, sort =TRUE) %>% 
#      mutate(
#        percent = paste0(round(n/sum(n)*100,2),"%") 
#      )

```

